config/routes.rb
Rails.application.routes.draw do
  
  resources :items
  resources :users
  resources :bids
  get '/' => "site#home"

end

app/models/bid.rb
class Bid < ActiveRecord::Base

  belongs_to :item
  belongs_to :user

  validates :amount, numericality: true
  
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :bids
  has_many :users, through: :bids
  
  validates :end_date, presence: true

  validate :proper_date




    def assign_winner
      self.update_attribute :winner_id, self.bids.last.user_id
    end

    def price_sold
      self.update_attribute :end_price, self.bids.last.amount
    end

    def total_bids
      self.update_attribute :total_bid_num, self.bids.size
    end

  private
    def proper_date
      if end_date < Date.today
        errors.add( :end_date, "Wrong date")
      end
    end

end
 

app/models/user.rb
class User < ActiveRecord::Base

  has_many :bids
  has_many :items, through: :bids
  
  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController

  def create
    @bid = Bid.new bid_params
    @bid.save
    
    redirect_to item_path(@bid.item_id)
  end

  

 private
    def bid_params
      params.require(:bid).permit(:item_id, :user_id, :amount)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
      @items = Item.all.where("end_date > ?",Date.today) 
    end

    def new
      @item = Item.new
    end

    def create
      @item = Item.new item_params

      if @item.save
        redirect_to action: 'index'
      else
        render 'new'
      end
    end

    def show
      @item = Item.find params[:id]
      @users = User.all
      @bid = Bid.new
    end

    def destroy
      @item = Item.find params[:id]
      @item.destroy
      redirect_to action: 'index'
    end

    private
    def item_params
      params.require(:item).permit(:name, :end_date)
    end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      redirect_to users_path
    else
      render 'new'
    end
  end



  private
   
    def user_params
      params.require(:user).permit(:email) 
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/index.html.erb
<p>That's all the stuff we have </p>

<ul >
  <% @items.each do |item| %>
    <li>
      <span><%= link_to(item.name, item_path(item.id)) %></span>
    </li>
  <% end %>
</ul>


<%= link_to("Add new Item", new_item_path) %>

app/views/items/new.html.erb
<h3>New Auction</h3>
<p>New Item to Bid</p>
<%= form_for @item do |f| %>

  

      <%= f.label :name %>
      <%= f.text_field :name, placeholder: "Item name" %>

      <%= f.label "End of the auction date" %>
      <%= f.date_field :end_date %>
  
    <%= f.submit 'Publish Auction' %>
  
<% end %>

app/views/items/show.html.erb
<h2><%= @item.name %></h2>
<p><span><%= @item.end_date %></span></p>




<%= form_for @bid do |f| %>
  <%= f.hidden_field :item_id, value: @item.id %>


      <%= f.label "Enter your user to bid" %>
      <%= f.text_field :user_id %>
  
      <%= f.label "€" %>
      <%= f.number_field :amount, placeholder: "99,99" %>

    <%= f.submit 'Save bid' %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AuctionSite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <div class="container">
  <div class="row">
    <ul class="nav nav-pills">
    
      <li role="presentation" class="active"><%= link_to("Home", '/') %></li>
      <li role="presentation"><%= link_to("Auctions", items_path) %></li>
      <li role="presentation"><%= link_to("Users", users_path) %></li>
  
      </ul>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-md-6 .col-md-offset-3">

    <%= yield %>
      
      </div>
    </div>
  </div>
</body>
</html>

app/views/site/home.html.erb
<h2> THAT'S THE HOME PAGE </h2>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>


      <%= f.label :email %>
      <%= f.email_field :email, placeholder: "example@mail.com" %>

  
    <%= f.submit 'Sign in' %>


<% end %>

app/views/users/index.html.erb
<ul>
  <% @users.each do |user| %>
  <li>
    <p><%= user.email %></p>
  </li>
  <% end %>
</ul>


<%= link_to("Join now and start biding :D", new_user_path) %>

app/views/users/new.html.erb
<%= render 'form' %>